# Generated by Django 4.0.2 on 2022-07-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('TG', 'TransGender')], max_length=11)),
                ('qualifiaction', models.CharField(choices=[('ECE', 'Electronics & Communication Engineering'), ('CSE', 'Computer Science Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering')], max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
            ],
        ),
    ]
