# Generated by Django 4.0.4 on 2022-07-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FB_CRUD_APP', '0002_rename_qualifiaction_student_qualification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='occupation',
            new_name='college',
        ),
        migrations.RemoveField(
            model_name='student',
            name='qualification',
        ),
        migrations.AddField(
            model_name='student',
            name='engineering_stream',
            field=models.CharField(choices=[('ECE', 'Electronics & Communication Engineering'), ('CSE', 'Computer Science Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('EEE', 'Electrical & Electronics Engineering'), ('ISE', 'Information Science Engineering'), ('AE', 'Aeronautical Engineering')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=11),
        ),
    ]
