# Generated by Django 4.0.4 on 2022-07-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FB_CRUD_APP', '0003_rename_occupation_student_college_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.CharField(max_length=200),
        ),
    ]
